xc.depends([
  "Bitmap.js",
  "BitmapAnimation.js",
  "Container.js",
  "DisplayObject.js",
  "Graphics.js",
  "MovieClip.js",
  "Shadow.js",
  "Shape.js",
  "SpriteSheet.js",
  "Stage.js",
  "Text.js"
]);
